### ISSUE TITLE
Cannot assign to read only property '0' of object '[object Array]'

### ISSUE THREAD

**Issue by codylv7** [kalkih/mini-graph-card#287]
Still get this error after updating card to v0.9.3

I have cleared browser cache and reinstalled the card from HACS just to be sure.

**Comment by toofewacres** [comment]
I started getting this error also when I updated HA to 106.0 Always work fine prior to this

**Comment by wencevdm** [comment]
Still getting this error on v0.9.3 with HA 0.106.1.

**Comment by abstrakct** [comment]
Same error for me as well. Everything is updated, all cache cleared. HA 0.106.1 and v0.9.3 of mini-graph-card.

**Comment by kamarmic** [comment]
Same here. Seems to be due to **color_thresholds**, and having multiple items in the list. With a single item, the error goes away, but >1 list item and I get the above error.

**Comment by wencevdm** [comment]
> Same here. Seems to be due to **color_thresholds**, and having multiple items in the list. With a single item, the error goes away, but >1 list item and I get the above error.

Not using any color_thresholds here, though still have the error.

**Comment by kalkih** [comment]
#274, #275, #284, #285, #286 
Please everyone, try looking for existing issues before opening new ones.
This has been fixed in the latest version of the card released a few days back.

If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:

* Reinstall the card in HACS (if installed though HACS) 
* Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169
* Clear browser cache

If you still have issues after this, open the browser developer console (google how to do this) and look for a line which says "MINI-GRAPH-CARD" followed by the version number and let me know what version it says.

**Comment by wencevdm** [comment]
@kalkih You're 100% right, looks like the card didn't actually update, even though HACS said it did. Had to remove/reinstall to get it to work, and now everything is fine and dandy, thanks!

**Comment by codylv7** [comment]
As I said in my original post, I cleared browser cache (made sure by opening in incognito mode), reinstalled from HACS (uninstall then install) and when I look at dev console i don't even see the card loading even though I see it on sources tab.  I would not of posted a duplicate issue if my original one hadn't been closed without actually verifying it was working.  In any case, I will try to manually install latest version and see if it fixes the problem.

![image](https://user-images.githubusercontent.com/40413816/75563004-69cf9b00-59fe-11ea-8429-a8adf806e5fc.png)

**Comment by codylv7** [comment]
Installed latest release manually, cleared cache, still getting error.

**Comment by abstrakct** [comment]
Uninstall and install (via HACS) worked for me! I also found an old resource reference in my ui-lovelace.yaml, which I fixed as per issue #169. That might have been what caused the old version of the card to be loaded.

**Comment by codylv7** [comment]
Question, should I be adding ?v0.9.3 to the end of the reference in my ui-lovelace file?  I haven't done that since I started using HACS, but if it's necessary, I'll add it.

**Comment by kalkih** [comment]
> As I said in my original post, I cleared browser cache (made sure by opening in incognito mode), reinstalled from HACS (uninstall then install) and when I look at dev console i don't even see the card loading even though I see it on sources tab. I would not of posted a duplicate issue if my original one hadn't been closed without actually verifying it was working. In any case, I will try to manually install latest version and see if it fixes the problem.
> 
> ![image](https://user-images.githubusercontent.com/40413816/75563004-69cf9b00-59fe-11ea-8429-a8adf806e5fc.png)

You should see the MINI GRAPH CARD version printed in the console if you are running card version 0.9.0 or later. So you're still not loading the updated card, does the resource reference match with the location you got the updated card version js file?
Try incognito mode/another browser.

> Question, should I be adding ?v0.9.3 to the end of the reference in my ui-lovelace file? I haven't done that since I started using HACS, but if it's necessary, I'll add it.

You should only ever add this if you've installed the card manually, it's not necessary but can be useful when you update the card, since the url is changed it will force all browsers to load the new version of the code and not the cached version, which usually can be an issue.

**Comment by SteveDinn** [comment]
One thing I noticed, was that I uninstalled and reinstalled, the URL changed from
/community_plugin/mini-graph-card/mini-graph-card.js
to
/community_plugin/mini-graph-card/mini-graph-card-bundle.js 

Just upgrading normally via HACS, this did not change. When I updated the URL, everything worked again.

**Comment by kalkih** [comment]
Yes, this is a known issue #169 hence why I recommended checking the resource reference.
> If you still have the issue after updating the card that means your browser isn't loading the updated version of the card. Try the following:
> 
> * Reinstall the card in HACS (if installed though HACS)
> * **Double check the resource reference (if installed though HACS), make sure it match the one in HACS #169**
> * Clear browser cache
