### ISSUE TITLE
Zero values show as current value

### ISSUE THREAD

**Issue by kloggy** [kalkih/mini-graph-card#41]
It appears that whilst the line graph is correct, hovering over a zero value displays the current value.

![image](https://user-images.githubusercontent.com/38220016/52517965-75a5bf00-2c3b-11e9-8a0f-266f44483bd9.png)

![image](https://user-images.githubusercontent.com/38220016/52517948-40996c80-2c3b-11e9-9b0f-01219b21146d.png)

![image](https://user-images.githubusercontent.com/38220016/52517956-5d35a480-2c3b-11e9-8465-edce73ffe313.png)

**Comment by kloggy** [comment]
There is definitely something strange going on when the value is zero. This is how my graph looks now;

![image](https://user-images.githubusercontent.com/38220016/52541225-9df00380-2d8a-11e9-9100-3c35ed571e18.png)

![image](https://user-images.githubusercontent.com/38220016/52541229-a3e5e480-2d8a-11e9-90c8-15de9cea45bc.png)

![image](https://user-images.githubusercontent.com/38220016/52541231-a9432f00-2d8a-11e9-8d71-1dff450f4b65.png)

**Comment by kalkih** [comment]
There's a fix for this in the `dev` branch already, will be included in the next release, I'll let you know when it's ready, thanks! 😃

**Comment by kalkih** [comment]
@kloggy Should be fixed in the latest release, please confirm it's working if you can 👍

**Comment by kloggy** [comment]
Sorry for the slow reply.
I still get 1% sometimes when it should be zero. I know this isn't a great response but I can happily live with this (and put it down to rounding errors). However I am more than happy to help in any way I can if you want to track down what is going on.

![image](https://user-images.githubusercontent.com/38220016/52889314-4204f080-3177-11e9-9c8e-4b5080724997.png)

![image](https://user-images.githubusercontent.com/38220016/52889337-56e18400-3177-11e9-9b6e-e0c182e2979a.png)

**Comment by kloggy** [comment]
Today it is working perfectly. I'm happy to close this if you are.

**Comment by kalkih** [comment]
Hey @kloggy,
Great to hear.
Is it possible that maybe the cache didn't clear properly at first after you updated to the latest version?

From my testing it seems to work as expected now as well.
<img width="413" alt="screenshot 2019-02-18 at 00 29 47" src="https://user-images.githubusercontent.com/457678/52921177-b1641700-3314-11e9-9fce-6d4c885b86e9.png">

I'll go ahead and close this issue, thanks for the help!

**Comment by chriscrowe** [comment]
I'm still seeing this issue on the latest version...

https://imgur.com/a/lN4gqfW

https://pastebin.com/zb0AuNH0

**Comment by kalkih** [comment]
Hey, would be great if you could pull the history data and send it to me.

I'm not able to reproduce this myself.

**Comment by chriscrowe** [comment]
Sorry I thought I did that on my pastebin. How do I pull the history?

**Comment by kalkih** [comment]
Sorry, was on mobile so missed that link, great, I'll take a look when I got some time.

**Comment by kalkih** [comment]
Can you send me your card config also please.

**Comment by kalkih** [comment]
@chriscrowe I checked the data you sent me and the information displayed in the card looks to be correct, the latest history entry is actually "0.0" as the current state indicates.

The graph is based on the moving average, so depending on card config it could take time for you to clearly see the actual dip in the graph.

**Comment by chriscrowe** [comment]
Hm... So this smart plug is hooked up to a small refrigerator which cycles on and off, and in the off cycles it should be pulling nearly 0 watts. You can see 2 of the cycles in my mini-graph-card (the spikes) but it should be flat at zero between those cycles, similar to what you see in the Hassio history graph. Here's what my card config looks like:

```yaml
      - type: 'custom:mini-graph-card'
        name: Kegerator
        animate: true
        icon: mdi:fridge-outline
        entities:
          - entity: sensor.teckin4_wattage
            name: Kegerator
            color: '#6DA98B' # Lime Green 
        hours_to_show: 2
        points_per_hour: 30
        line_width: 4
        decimals: 0
        lower_bound: 0
        upper_bound: 260
        show:
          labels: true
```

**Comment by kalkih** [comment]
Thanks, noticed another issue related to your graph though, if there is missing history data between "data points" the last known "average" value will fill the missing data points, where instead the actual last known state should be used and not the average.

Fixing this will make the graph look like this instead.

![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/55244393-62799d80-5241-11e9-80bd-fa13c7591876.png)

**Comment by chriscrowe** [comment]
Yeah it seems to me that these plugs have some type of behavior which puts them into a sleep mode when you're not pulling a load on them, so we start getting null/missing values in the logs.

How did you make the graph in your screenshot? That does look pretty much like what I would expect.

**Comment by kalkih** [comment]
I made some changes to the source code. I will push these changes when I get home tomorrow, and it will be available next release.

Thanks for the data!

**Comment by chriscrowe** [comment]
@kalkih did this ever make its way into a release?

**Comment by kalkih** [comment]
Nope, not yet, I'll make a new release tomorrow.
Thanks for reminding me.

**Comment by chriscrowe** [comment]
Awesome thanks!

**Comment by kalkih** [comment]
@chriscrowe New release now available, please let me know if this fixed the issues you had.
