### ISSUE TITLE
"state_adaptive_color" option is confusing since the left "state" text is used for displaying states for all entities

### ISSUE THREAD

**Issue by ildar170975** [kalkih/mini-graph-card#698]
The `state_adaptive_color` may be used to visually associate a displayed state with a corresponding graph:
![image](https://user-images.githubusercontent.com/71872483/150060172-7f9159fd-4c88-4c52-b34a-4e64348a99a7.png)
```
type: custom:mini-graph-card
entities:
  - entity: sensor.cleargrass_1_temperature
    name: Temp
    show_state: true
    color: red
    state_adaptive_color: true
  - entity: sensor.cleargrass_2_co2
    name: CO2
    show_state: true
    color: green
    state_adaptive_color: true
    y_axis: secondary
show:
  name: false
  icon: false
```
If some point is selected on the 2nd graph then the left "state" text contains a value for this point:
![image](https://user-images.githubusercontent.com/71872483/150060372-54bee89f-d1b9-433a-92a1-80295f2ac595.png)
This confuses since the label has a value for the 2nd entity and a color for the 1st entity.

**Suggestion:**
If some point is selected for some entity and this entity has the `state_adaptive_color: true` option, then set the text color **accordingly to this entity**.

**Comment by akloeckner** [comment]
fixed in #1214

**Comment by ildar170975** [comment]
There is still a problem.
Assume we have `state_adaptive_color: true` for ONE entity defined only:
```
type: custom:mini-graph-card
entities:
  - entity: sensor.xiaomi_cg_1_co2
    color: red

  - entity: sensor.xiaomi_cg_2_co2
    show_state: true
    color: green
    state_adaptive_color: true
```
Then the 2nd entity's state is not colored when SELECTED:
![Image](https://github.com/user-attachments/assets/aa86abf7-3354-4ba0-ab40-5a0f8448e890)

**Comment by ildar170975** [comment]
With https://github.com/kalkih/mini-graph-card/pull/1217 I see the issue fixed.

**Comment by Pampasgras** [comment]
Not sure if this is related:

When having only 1 entity, and state_adaptive_color = true
--> it doesn't change color when a specific datapoint is selected (while the icon does when icon_adaptive_color = true)

In the screenshot a green value is selected, the icon is green, the value of the state is updated according to the selected datapoint, but the color isn't
![Image](https://github.com/user-attachments/assets/b06c922e-8f39-4ac0-b8f0-c01474f90117)

**Comment by ildar170975** [comment]
@Pampasgras 
Please post a code for the card. 
Also, check if you have the latest dev version.

**Comment by Pampasgras** [comment]
type: custom:mini-graph-card
name: Vermogen (grafiek 24h)
hours_to_show: 24
points_per_hour: 15
height: 300
line_width: 3
hour24: true
color_thresholds_transition: hard
smoothing: false
align_state: right
entities:
  - entity: sensor.p1_meter_power
    state_adaptive_color: true
show:
  fill: fade
  icon_adaptive_color: true
  labels: true
color_thresholds:
  - value: -2500
    color: "#008800"
  - value: 0
    color: "#ff8800"
  - value: 2500
    color: "#ff0000"
