### ISSUE TITLE
v0.4.1, Cards not showing if "color_threshold" is not defined in yaml

### ISSUE THREAD

**Issue by DoctorOctagonapus** [kalkih/mini-graph-card#92]
Updated the mini-graph-card js to 0.4.1, and most of my graph cards disappeared. While investigating the problem I discovered only the cards with a defined "color_threshold" section in the yaml will display. As soon as that is removed, the card vanishes, even if there is a "color" value defined.

No error message is shown, just empty space.

Mock-up example of a working card (taken from elsewhere in my setup)
![Screen Shot 2019-05-17 at 22 00 12](https://user-images.githubusercontent.com/6576477/57955993-58922380-78ef-11e9-9f3e-4787b0cba4f8.png)

And as soon as I remove the two lines on the bottom:
![Screen Shot 2019-05-17 at 22 00 27](https://user-images.githubusercontent.com/6576477/57955994-58922380-78ef-11e9-82bd-558fa4d35d83.png)

This is only since updating to 0.4.1; previous versions worked fine.

**Comment by kalkih** [comment]
Hey,
Please try re-downloading the latest release, might be that the build didn't deploy on time of the release properly, also try clearing cache.

**Comment by DoctorOctagonapus** [comment]
Clearing the cache and hard-reloading the page seemed to bring my graphs back, but I've also noticed the actual line on the graph is missing from cards with the color_threshold defined. This is also in the two screenshots I posted in the original issue.

Replacing the js file with one from the latest release doesn't seem to have made a difference.

**Comment by kalkih** [comment]
Can't reproduce, please post any potential errors found in the browser dev console.

And, while I can't reproduce this particular issue, there's a few other issues with the new color_thresholds implementation, woking on improving it atm.

**Comment by tomlut** [comment]
Seeing the same issue. Lines are no longer showing up, on some graphs. These all have the same config and until this update all had lines visible:

![Untitled](https://user-images.githubusercontent.com/10679300/57965571-62686500-7989-11e9-812e-44bb5a4f8ee2.png)

Cant see any reason why some graphs have lines and others dont.

**Comment by kalkih** [comment]
Hey, [new release](https://github.com/kalkih/mini-graph-card/releases/tag/v0.4.2) should fix these issues.

**Comment by tomlut** [comment]
Still broken unfortunately. Lines missing on graphs that do not cross colour thresholds and line colour history only shows up correctly on mouse hover. 

I cleared my cache but it made no difference.

![Untitled](https://user-images.githubusercontent.com/10679300/57970267-a592fa00-79c2-11e9-9d12-13b974b4b37f.png)

**Comment by kalkih** [comment]
Okay, I see the issue with line color not showing if line never cross a threshold, should be an easy fix.

The other issue is kinda weird though, I see it now too, adding a second (non existing entity) to the graph seems to fix it?
Not sure what that could be, I'm really tired of all this SVG stuff atm to be honest... thinking about rolling back to the old threshold solution. 😆

**Comment by kalkih** [comment]
> Not sure what that could be, I'm really tired of all this SVG stuff atm to be honest... thinking about rolling back to the old threshold solution. 😆

Setting `hours_to_show` higher (100 or something) also seems to solve the second issue, I'm confused 🤔

**Comment by DoctorOctagonapus** [comment]
I'd suggest either rolling back or putting in a switch option to specify how to draw the threshold colour change.

**Comment by kalkih** [comment]
Nah, I'm going to fix this, in the meantime, If you need color_thresholds working properly rn, go and download the [v0.3.3](https://github.com/kalkih/mini-graph-card/releases/tag/v0.3.3) release.

**Comment by kalkih** [comment]
Hey everyone, new pre-release available, would appreciate your feedback, should fix the issues discussed here.
https://github.com/kalkih/mini-graph-card/releases/tag/v0.4.3-beta

**Comment by tomlut** [comment]
Yep the beta release works as expected for me. Thank you for the rapid fix.

**Comment by bratanon** [comment]
The lines is back with 0.4.3. 

Not sure if I have missed anything here (comming from 0.3.3) but the has the _color_thresholds_ changed?

`
line_color: var(--google-green-400)
color_thresholds:
  - value: 50
    color: var(--google-red-400)
`
with a value of 0 (zero) will print a red line.

**Comment by kalkih** [comment]
@bratanon 
color thresholds no longer fall back to line_color if unmet, so you'll have to specify another threshold entry for the green color in your example.

**Comment by tomlut** [comment]
The only thing I would say is that the transition between colours on the graph line seems a bit broad. So much so that it often appears that the line is in the next threshold colour. In the ilages below the mouse hover shows the correct colour thresholds
![hover_mouse](https://user-images.githubusercontent.com/10679300/58063007-d5f3b780-7bbf-11e9-8e95-16946233cf43.png)
![no_mouse](https://user-images.githubusercontent.com/10679300/58063008-d68c4e00-7bbf-11e9-8e16-16fd062bde3a.png)

:

**Comment by bratanon** [comment]
@tomlut Yes, I have that issue too.

**Comment by bratanon** [comment]
```
show:
  fill: false
  labels: false
hour24: true
more_info: false
color_thresholds:
  - value: 0
    color: var(--google-green-400)
  - value: 50
    color: var(--google-red-400)
```
The lowest value in the graph is 0, and the highest is 0.2 and that will produce a red line in the end.

![Screenshot from 2019-05-21 16-59-53](https://user-images.githubusercontent.com/812265/58107343-e7ea5000-7be9-11e9-989d-0b5357c2a9b9.png)

**Comment by kalkih** [comment]
@tomlut @bratanon 

Yep, that's a caveat of the new way we render thresholds.
It can however be circumvented by adding an additional threshold, and that way the transition "smoothness" could also be adjusted.
This would also work for values out of bounds of the rendered graph.

![hyperion_8123_lovelace_4](https://user-images.githubusercontent.com/457678/58110138-3e0dc200-7bef-11e9-9556-0603a3f3cdb2.png)
```yaml
- type: custom:mini-graph-card
  entities:
    - sensor.example
  name: Soft
  color_thresholds:
    - value: 10
      color: "#81ecec" # TEAL
    - value: 20
      color: "#e74c3c" # RED
```

![hyperion_8123_lovelace_4 (1)](https://user-images.githubusercontent.com/457678/58110222-6c8b9d00-7bef-11e9-9242-067d2ed41701.png)
```yaml
- type: custom:mini-graph-card
  entities:
    - sensor.example
  name: Hard
  color_thresholds:
    - value: 10
      color: "#81ecec" # TEAL
    - value: 19.9
      color: "#81ecec" # TEAL
    - value: 20
      color: "#e74c3c" # RED
```

I can see the current behaviour being useful if you don't really care about values and just want a gradient effect, low -> high.

We could solve the issue programmatically but would then lose the ability to have smooth transitions, and would also make the use case stated above unachievable. But yeah, it's the "out of bounds" thresholds that's the main issue.

If you can think of another solution, I would love to hear it.

**Comment by kalkih** [comment]
Let's continue the discussion about color thresholds in #91, as the original issue of this topic is resolved.
